# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ParadiddleUtilities.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParadiddleUtilities(object):
    def setupUi(self, ParadiddleUtilities):
        ParadiddleUtilities.setObjectName("ParadiddleUtilities")
        ParadiddleUtilities.resize(600, 517)
        ParadiddleUtilities.setStyleSheet("QLabel {\n"
"  font-size: 12px\n"
"}\n"
"\n"
"QPushButton {\n"
"  font-size: 12px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ParadiddleUtilities)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.selectMidiButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectMidiButton.setGeometry(QtCore.QRect(450, 70, 121, 23))
        self.selectMidiButton.setObjectName("selectMidiButton")
        self.selectDrumSetButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectDrumSetButton.setGeometry(QtCore.QRect(450, 30, 121, 23))
        self.selectDrumSetButton.setObjectName("selectDrumSetButton")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(240, 430, 111, 31))
        self.convertButton.setObjectName("convertButton")
        self.drumSetLabel = QtWidgets.QLabel(self.centralwidget)
        self.drumSetLabel.setGeometry(QtCore.QRect(30, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.drumSetLabel.setFont(font)
        self.drumSetLabel.setObjectName("drumSetLabel")
        self.midiFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.midiFileLabel.setGeometry(QtCore.QRect(30, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.midiFileLabel.setFont(font)
        self.midiFileLabel.setObjectName("midiFileLabel")
        self.audioFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.audioFileLabel.setGeometry(QtCore.QRect(30, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.audioFileLabel.setFont(font)
        self.audioFileLabel.setObjectName("audioFileLabel")
        self.selectAudioFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectAudioFileButton.setGeometry(QtCore.QRect(450, 110, 121, 23))
        self.selectAudioFileButton.setObjectName("selectAudioFileButton")
        self.songPlaybackOffsetLabel = QtWidgets.QLabel(self.centralwidget)
        self.songPlaybackOffsetLabel.setGeometry(QtCore.QRect(30, 150, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.songPlaybackOffsetLabel.setFont(font)
        self.songPlaybackOffsetLabel.setWordWrap(True)
        self.songPlaybackOffsetLabel.setObjectName("songPlaybackOffsetLabel")
        self.calibrationSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.calibrationSpinBox.setGeometry(QtCore.QRect(180, 150, 62, 21))
        self.calibrationSpinBox.setDecimals(3)
        self.calibrationSpinBox.setSingleStep(0.01)
        self.calibrationSpinBox.setObjectName("calibrationSpinBox")
        self.metadataLabel = QtWidgets.QLabel(self.centralwidget)
        self.metadataLabel.setGeometry(QtCore.QRect(30, 220, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.metadataLabel.setFont(font)
        self.metadataLabel.setObjectName("metadataLabel")
        self.separator = QtWidgets.QFrame(self.centralwidget)
        self.separator.setGeometry(QtCore.QRect(30, 190, 541, 20))
        self.separator.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator.setObjectName("separator")
        self.songName = QtWidgets.QLabel(self.centralwidget)
        self.songName.setGeometry(QtCore.QRect(30, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.songName.setFont(font)
        self.songName.setObjectName("songName")
        self.artistNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.artistNameLabel.setGeometry(QtCore.QRect(30, 280, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.artistNameLabel.setFont(font)
        self.artistNameLabel.setObjectName("artistNameLabel")
        self.authorNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.authorNameLabel.setGeometry(QtCore.QRect(310, 250, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.authorNameLabel.setFont(font)
        self.authorNameLabel.setObjectName("authorNameLabel")
        self.coverImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.coverImageLabel.setGeometry(QtCore.QRect(310, 280, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.coverImageLabel.setFont(font)
        self.coverImageLabel.setObjectName("coverImageLabel")
        self.description = QtWidgets.QLabel(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(30, 310, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setObjectName("description")
        self.drumSetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.drumSetLineEdit.setGeometry(QtCore.QRect(110, 30, 321, 20))
        self.drumSetLineEdit.setReadOnly(True)
        self.drumSetLineEdit.setObjectName("drumSetLineEdit")
        self.midiFileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.midiFileLineEdit.setGeometry(QtCore.QRect(110, 70, 321, 20))
        self.midiFileLineEdit.setReadOnly(True)
        self.midiFileLineEdit.setObjectName("midiFileLineEdit")
        self.audioFileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.audioFileLineEdit.setGeometry(QtCore.QRect(110, 110, 321, 20))
        self.audioFileLineEdit.setReadOnly(True)
        self.audioFileLineEdit.setObjectName("audioFileLineEdit")
        self.descriptionTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.descriptionTextEdit.setGeometry(QtCore.QRect(30, 340, 541, 71))
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.songNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.songNameLineEdit.setGeometry(QtCore.QRect(120, 250, 161, 20))
        self.songNameLineEdit.setObjectName("songNameLineEdit")
        self.artistNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.artistNameLineEdit.setGeometry(QtCore.QRect(120, 280, 161, 20))
        self.artistNameLineEdit.setObjectName("artistNameLineEdit")
        self.coverImageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.coverImageLineEdit.setGeometry(QtCore.QRect(410, 280, 121, 20))
        self.coverImageLineEdit.setReadOnly(True)
        self.coverImageLineEdit.setObjectName("coverImageLineEdit")
        self.authorNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.authorNameLineEdit.setGeometry(QtCore.QRect(410, 250, 161, 20))
        self.authorNameLineEdit.setObjectName("authorNameLineEdit")
        self.selectCoverImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectCoverImageButton.setGeometry(QtCore.QRect(540, 280, 31, 23))
        self.selectCoverImageButton.setObjectName("selectCoverImageButton")
        ParadiddleUtilities.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ParadiddleUtilities)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        ParadiddleUtilities.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ParadiddleUtilities)
        self.statusbar.setObjectName("statusbar")
        ParadiddleUtilities.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(ParadiddleUtilities)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ParadiddleUtilities)
        QtCore.QMetaObject.connectSlotsByName(ParadiddleUtilities)
        ParadiddleUtilities.setTabOrder(self.drumSetLineEdit, self.selectDrumSetButton)
        ParadiddleUtilities.setTabOrder(self.selectDrumSetButton, self.midiFileLineEdit)
        ParadiddleUtilities.setTabOrder(self.midiFileLineEdit, self.selectMidiButton)
        ParadiddleUtilities.setTabOrder(self.selectMidiButton, self.audioFileLineEdit)
        ParadiddleUtilities.setTabOrder(self.audioFileLineEdit, self.selectAudioFileButton)
        ParadiddleUtilities.setTabOrder(self.selectAudioFileButton, self.calibrationSpinBox)
        ParadiddleUtilities.setTabOrder(self.calibrationSpinBox, self.songNameLineEdit)
        ParadiddleUtilities.setTabOrder(self.songNameLineEdit, self.artistNameLineEdit)
        ParadiddleUtilities.setTabOrder(self.artistNameLineEdit, self.authorNameLineEdit)
        ParadiddleUtilities.setTabOrder(self.authorNameLineEdit, self.coverImageLineEdit)
        ParadiddleUtilities.setTabOrder(self.coverImageLineEdit, self.selectCoverImageButton)
        ParadiddleUtilities.setTabOrder(self.selectCoverImageButton, self.descriptionTextEdit)
        ParadiddleUtilities.setTabOrder(self.descriptionTextEdit, self.convertButton)

    def retranslateUi(self, ParadiddleUtilities):
        _translate = QtCore.QCoreApplication.translate
        ParadiddleUtilities.setWindowTitle(_translate("ParadiddleUtilities", "Paradiddle Utilities"))
        self.selectMidiButton.setText(_translate("ParadiddleUtilities", "Select Midi File"))
        self.selectDrumSetButton.setText(_translate("ParadiddleUtilities", "Select Drum Set"))
        self.convertButton.setText(_translate("ParadiddleUtilities", "Convert to .rlrr!"))
        self.drumSetLabel.setText(_translate("ParadiddleUtilities", "Drum Set:"))
        self.midiFileLabel.setText(_translate("ParadiddleUtilities", "Midi File:"))
        self.audioFileLabel.setText(_translate("ParadiddleUtilities", "Audio File:"))
        self.selectAudioFileButton.setText(_translate("ParadiddleUtilities", "Select Audio File"))
        self.songPlaybackOffsetLabel.setText(_translate("ParadiddleUtilities", "Song playback offset:"))
        self.metadataLabel.setText(_translate("ParadiddleUtilities", "Metadata"))
        self.songName.setText(_translate("ParadiddleUtilities", "Song Name:"))
        self.artistNameLabel.setText(_translate("ParadiddleUtilities", "Artist Name:"))
        self.authorNameLabel.setText(_translate("ParadiddleUtilities", "Author Name:"))
        self.coverImageLabel.setText(_translate("ParadiddleUtilities", "Cover Image:"))
        self.description.setText(_translate("ParadiddleUtilities", "Description:"))
        self.selectCoverImageButton.setText(_translate("ParadiddleUtilities", "..."))
        self.menuAbout.setTitle(_translate("ParadiddleUtilities", "Help"))
        self.actionAbout.setText(_translate("ParadiddleUtilities", "About"))

