# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ParadiddleUtilities.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParadiddleUtilities(object):
    def setupUi(self, ParadiddleUtilities):
        ParadiddleUtilities.setObjectName("ParadiddleUtilities")
        ParadiddleUtilities.resize(484, 481)
        self.centralwidget = QtWidgets.QWidget(ParadiddleUtilities)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.selectMidiButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectMidiButton.setGeometry(QtCore.QRect(30, 190, 121, 23))
        self.selectMidiButton.setObjectName("selectMidiButton")
        self.midiLabel = QtWidgets.QLabel(self.centralwidget)
        self.midiLabel.setGeometry(QtCore.QRect(30, 170, 191, 16))
        self.midiLabel.setWordWrap(True)
        self.midiLabel.setObjectName("midiLabel")
        self.selectDrumSetButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectDrumSetButton.setGeometry(QtCore.QRect(30, 80, 121, 23))
        self.selectDrumSetButton.setObjectName("selectDrumSetButton")
        self.selectedSetLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectedSetLabel.setGeometry(QtCore.QRect(30, 60, 201, 16))
        self.selectedSetLabel.setObjectName("selectedSetLabel")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(180, 390, 111, 31))
        self.convertButton.setObjectName("convertButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.midiLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.midiLabel_2.setGeometry(QtCore.QRect(30, 280, 191, 16))
        self.midiLabel_2.setWordWrap(True)
        self.midiLabel_2.setObjectName("midiLabel_2")
        self.selectMidiButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.selectMidiButton_2.setGeometry(QtCore.QRect(30, 300, 121, 23))
        self.selectMidiButton_2.setObjectName("selectMidiButton_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 110, 421, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 220, 421, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 370, 421, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.midiLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.midiLabel_3.setGeometry(QtCore.QRect(30, 340, 191, 21))
        self.midiLabel_3.setWordWrap(True)
        self.midiLabel_3.setObjectName("midiLabel_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(170, 340, 62, 21))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        ParadiddleUtilities.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ParadiddleUtilities)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 26))
        self.menubar.setObjectName("menubar")
        ParadiddleUtilities.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ParadiddleUtilities)
        self.statusbar.setObjectName("statusbar")
        ParadiddleUtilities.setStatusBar(self.statusbar)

        self.retranslateUi(ParadiddleUtilities)
        QtCore.QMetaObject.connectSlotsByName(ParadiddleUtilities)

    def retranslateUi(self, ParadiddleUtilities):
        _translate = QtCore.QCoreApplication.translate
        ParadiddleUtilities.setWindowTitle(_translate("ParadiddleUtilities", "Paradiddle Utilities"))
        self.selectMidiButton.setText(_translate("ParadiddleUtilities", "Select Midi File"))
        self.midiLabel.setText(_translate("ParadiddleUtilities", "No Midi File Selected"))
        self.selectDrumSetButton.setText(_translate("ParadiddleUtilities", "Select Drum Set"))
        self.selectedSetLabel.setText(_translate("ParadiddleUtilities", "Selected Drum Set: default.rlrr"))
        self.convertButton.setText(_translate("ParadiddleUtilities", "Convert to .rlrr!"))
        self.label.setText(_translate("ParadiddleUtilities", "Drum Set"))
        self.label_2.setText(_translate("ParadiddleUtilities", "Midi File"))
        self.label_3.setText(_translate("ParadiddleUtilities", "Audio File"))
        self.midiLabel_2.setText(_translate("ParadiddleUtilities", "No audio file selected"))
        self.selectMidiButton_2.setText(_translate("ParadiddleUtilities", "Select Audio File"))
        self.midiLabel_3.setText(_translate("ParadiddleUtilities", "Song playback offset:"))

