# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ParadiddleUtilities.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParadiddleUtilities(object):
    def setupUi(self, ParadiddleUtilities):
        ParadiddleUtilities.setObjectName("ParadiddleUtilities")
        ParadiddleUtilities.resize(600, 440)
        ParadiddleUtilities.setStyleSheet("\n"
"QLabel {\n"
"    font-size: 12px;\n"
"    font-style: bold;\n"
"}\n"
"\n"
"QPushButton {\n"
"  font-size: 12px;\n"
"}\n"
"\n"
"StatusLabel {\n"
"    color: red;\n"
"    font-size: 20px;\n"
"}\n"
"")
        ParadiddleUtilities.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(ParadiddleUtilities)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(319, 320, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.convertButton.setFont(font)
        self.convertButton.setObjectName("convertButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(0, 360, 601, 41))
        self.statusLabel.setStyleSheet("background-color: rgb(195, 195, 195)")
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 590, 300))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.drumSetTab = QtWidgets.QWidget()
        self.drumSetTab.setObjectName("drumSetTab")
        self.splitter = QtWidgets.QSplitter(self.drumSetTab)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 551, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.drumSetLabel = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumSetLabel.sizePolicy().hasHeightForWidth())
        self.drumSetLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.drumSetLabel.setFont(font)
        self.drumSetLabel.setObjectName("drumSetLabel")
        self.drumSetLineEdit = QtWidgets.QLineEdit(self.splitter)
        self.drumSetLineEdit.setReadOnly(True)
        self.drumSetLineEdit.setObjectName("drumSetLineEdit")
        self.selectDrumSetButton = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDrumSetButton.sizePolicy().hasHeightForWidth())
        self.selectDrumSetButton.setSizePolicy(sizePolicy)
        self.selectDrumSetButton.setMinimumSize(QtCore.QSize(100, 0))
        self.selectDrumSetButton.setObjectName("selectDrumSetButton")
        self.tabWidget.addTab(self.drumSetTab, "")
        self.midiTab = QtWidgets.QWidget()
        self.midiTab.setObjectName("midiTab")
        self.splitter_2 = QtWidgets.QSplitter(self.midiTab)
        self.splitter_2.setGeometry(QtCore.QRect(10, 10, 571, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.midiFileLabel = QtWidgets.QLabel(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midiFileLabel.sizePolicy().hasHeightForWidth())
        self.midiFileLabel.setSizePolicy(sizePolicy)
        self.midiFileLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.midiFileLabel.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.midiFileLabel.setFont(font)
        self.midiFileLabel.setObjectName("midiFileLabel")
        self.midiFileLineEdit = QtWidgets.QLineEdit(self.splitter_2)
        self.midiFileLineEdit.setReadOnly(True)
        self.midiFileLineEdit.setObjectName("midiFileLineEdit")
        self.selectMidiButton = QtWidgets.QPushButton(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectMidiButton.sizePolicy().hasHeightForWidth())
        self.selectMidiButton.setSizePolicy(sizePolicy)
        self.selectMidiButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectMidiButton.setObjectName("selectMidiButton")
        self.midiTrackLabel = QtWidgets.QLabel(self.midiTab)
        self.midiTrackLabel.setGeometry(QtCore.QRect(10, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.midiTrackLabel.setFont(font)
        self.midiTrackLabel.setObjectName("midiTrackLabel")
        self.midiTrackComboBox = QtWidgets.QComboBox(self.midiTab)
        self.midiTrackComboBox.setGeometry(QtCore.QRect(90, 40, 181, 22))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.midiTrackComboBox.setFont(font)
        self.midiTrackComboBox.setEditable(False)
        self.midiTrackComboBox.setCurrentText("")
        self.midiTrackComboBox.setMinimumContentsLength(1)
        self.midiTrackComboBox.setObjectName("midiTrackComboBox")
        self.difficultyLabel = QtWidgets.QLabel(self.midiTab)
        self.difficultyLabel.setGeometry(QtCore.QRect(10, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.difficultyLabel.setFont(font)
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.difficultyComboBox = QtWidgets.QComboBox(self.midiTab)
        self.difficultyComboBox.setGeometry(QtCore.QRect(90, 70, 181, 22))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.difficultyComboBox.setFont(font)
        self.difficultyComboBox.setEditable(False)
        self.difficultyComboBox.setMinimumContentsLength(1)
        self.difficultyComboBox.setObjectName("difficultyComboBox")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.splitter_12 = QtWidgets.QSplitter(self.midiTab)
        self.splitter_12.setGeometry(QtCore.QRect(10, 100, 561, 23))
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.midiMappingLabel = QtWidgets.QLabel(self.splitter_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midiMappingLabel.sizePolicy().hasHeightForWidth())
        self.midiMappingLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.midiMappingLabel.setFont(font)
        self.midiMappingLabel.setObjectName("midiMappingLabel")
        self.midiMappingLineEdit = QtWidgets.QLineEdit(self.splitter_12)
        self.midiMappingLineEdit.setReadOnly(True)
        self.midiMappingLineEdit.setObjectName("midiMappingLineEdit")
        self.selectMidiMappingButton = QtWidgets.QPushButton(self.splitter_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectMidiMappingButton.sizePolicy().hasHeightForWidth())
        self.selectMidiMappingButton.setSizePolicy(sizePolicy)
        self.selectMidiMappingButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectMidiMappingButton.setObjectName("selectMidiMappingButton")
        self.tabWidget.addTab(self.midiTab, "")
        self.audioTab = QtWidgets.QWidget()
        self.audioTab.setObjectName("audioTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.audioTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 571, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setMinimumSize(QtCore.QSize(0, 10))
        self.splitter_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.songTrackLabel_1 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLabel_1.sizePolicy().hasHeightForWidth())
        self.songTrackLabel_1.setSizePolicy(sizePolicy)
        self.songTrackLabel_1.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.songTrackLabel_1.setFont(font)
        self.songTrackLabel_1.setObjectName("songTrackLabel_1")
        self.songTrackLineEdit_1 = QtWidgets.QLineEdit(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLineEdit_1.sizePolicy().hasHeightForWidth())
        self.songTrackLineEdit_1.setSizePolicy(sizePolicy)
        self.songTrackLineEdit_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.songTrackLineEdit_1.setBaseSize(QtCore.QSize(0, 0))
        self.songTrackLineEdit_1.setReadOnly(True)
        self.songTrackLineEdit_1.setObjectName("songTrackLineEdit_1")
        self.selectSongTrackButton_1 = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSongTrackButton_1.sizePolicy().hasHeightForWidth())
        self.selectSongTrackButton_1.setSizePolicy(sizePolicy)
        self.selectSongTrackButton_1.setMinimumSize(QtCore.QSize(0, 0))
        self.selectSongTrackButton_1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectSongTrackButton_1.setObjectName("selectSongTrackButton_1")
        self.verticalLayout.addWidget(self.splitter_3)
        self.splitter_4 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        self.splitter_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.audioFileLabel_2 = QtWidgets.QLabel(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audioFileLabel_2.sizePolicy().hasHeightForWidth())
        self.audioFileLabel_2.setSizePolicy(sizePolicy)
        self.audioFileLabel_2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.audioFileLabel_2.setFont(font)
        self.audioFileLabel_2.setObjectName("audioFileLabel_2")
        self.songTrackLineEdit_2 = QtWidgets.QLineEdit(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLineEdit_2.sizePolicy().hasHeightForWidth())
        self.songTrackLineEdit_2.setSizePolicy(sizePolicy)
        self.songTrackLineEdit_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.songTrackLineEdit_2.setBaseSize(QtCore.QSize(0, 0))
        self.songTrackLineEdit_2.setReadOnly(True)
        self.songTrackLineEdit_2.setObjectName("songTrackLineEdit_2")
        self.selectSongTrackButton_2 = QtWidgets.QPushButton(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSongTrackButton_2.sizePolicy().hasHeightForWidth())
        self.selectSongTrackButton_2.setSizePolicy(sizePolicy)
        self.selectSongTrackButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.selectSongTrackButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectSongTrackButton_2.setObjectName("selectSongTrackButton_2")
        self.verticalLayout.addWidget(self.splitter_4)
        self.splitter_5 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.songTrackLabel_3 = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLabel_3.sizePolicy().hasHeightForWidth())
        self.songTrackLabel_3.setSizePolicy(sizePolicy)
        self.songTrackLabel_3.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.songTrackLabel_3.setFont(font)
        self.songTrackLabel_3.setObjectName("songTrackLabel_3")
        self.songTrackLineEdit_3 = QtWidgets.QLineEdit(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLineEdit_3.sizePolicy().hasHeightForWidth())
        self.songTrackLineEdit_3.setSizePolicy(sizePolicy)
        self.songTrackLineEdit_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.songTrackLineEdit_3.setBaseSize(QtCore.QSize(0, 0))
        self.songTrackLineEdit_3.setReadOnly(True)
        self.songTrackLineEdit_3.setObjectName("songTrackLineEdit_3")
        self.selectSongTrackButton_3 = QtWidgets.QPushButton(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSongTrackButton_3.sizePolicy().hasHeightForWidth())
        self.selectSongTrackButton_3.setSizePolicy(sizePolicy)
        self.selectSongTrackButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.selectSongTrackButton_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectSongTrackButton_3.setObjectName("selectSongTrackButton_3")
        self.verticalLayout.addWidget(self.splitter_5)
        self.splitter_6 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_6.sizePolicy().hasHeightForWidth())
        self.splitter_6.setSizePolicy(sizePolicy)
        self.splitter_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.songTrackLabel_4 = QtWidgets.QLabel(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLabel_4.sizePolicy().hasHeightForWidth())
        self.songTrackLabel_4.setSizePolicy(sizePolicy)
        self.songTrackLabel_4.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.songTrackLabel_4.setFont(font)
        self.songTrackLabel_4.setObjectName("songTrackLabel_4")
        self.songTrackLineEdit_4 = QtWidgets.QLineEdit(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLineEdit_4.sizePolicy().hasHeightForWidth())
        self.songTrackLineEdit_4.setSizePolicy(sizePolicy)
        self.songTrackLineEdit_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.songTrackLineEdit_4.setBaseSize(QtCore.QSize(0, 0))
        self.songTrackLineEdit_4.setReadOnly(True)
        self.songTrackLineEdit_4.setObjectName("songTrackLineEdit_4")
        self.selectSongTrackButton_4 = QtWidgets.QPushButton(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSongTrackButton_4.sizePolicy().hasHeightForWidth())
        self.selectSongTrackButton_4.setSizePolicy(sizePolicy)
        self.selectSongTrackButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.selectSongTrackButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectSongTrackButton_4.setObjectName("selectSongTrackButton_4")
        self.verticalLayout.addWidget(self.splitter_6)
        self.splitter_9 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_9.sizePolicy().hasHeightForWidth())
        self.splitter_9.setSizePolicy(sizePolicy)
        self.splitter_9.setMinimumSize(QtCore.QSize(0, 10))
        self.splitter_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.songTrackLabel_5 = QtWidgets.QLabel(self.splitter_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLabel_5.sizePolicy().hasHeightForWidth())
        self.songTrackLabel_5.setSizePolicy(sizePolicy)
        self.songTrackLabel_5.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.songTrackLabel_5.setFont(font)
        self.songTrackLabel_5.setObjectName("songTrackLabel_5")
        self.songTrackLineEdit_5 = QtWidgets.QLineEdit(self.splitter_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songTrackLineEdit_5.sizePolicy().hasHeightForWidth())
        self.songTrackLineEdit_5.setSizePolicy(sizePolicy)
        self.songTrackLineEdit_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.songTrackLineEdit_5.setBaseSize(QtCore.QSize(0, 0))
        self.songTrackLineEdit_5.setReadOnly(True)
        self.songTrackLineEdit_5.setObjectName("songTrackLineEdit_5")
        self.selectSongTrackButton_5 = QtWidgets.QPushButton(self.splitter_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSongTrackButton_5.sizePolicy().hasHeightForWidth())
        self.selectSongTrackButton_5.setSizePolicy(sizePolicy)
        self.selectSongTrackButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.selectSongTrackButton_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectSongTrackButton_5.setObjectName("selectSongTrackButton_5")
        self.verticalLayout.addWidget(self.splitter_9)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setMinimumSize(QtCore.QSize(30, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_7 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_7.sizePolicy().hasHeightForWidth())
        self.splitter_7.setSizePolicy(sizePolicy)
        self.splitter_7.setMinimumSize(QtCore.QSize(0, 10))
        self.splitter_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.drumTrackLabel_1 = QtWidgets.QLabel(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLabel_1.sizePolicy().hasHeightForWidth())
        self.drumTrackLabel_1.setSizePolicy(sizePolicy)
        self.drumTrackLabel_1.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.drumTrackLabel_1.setFont(font)
        self.drumTrackLabel_1.setObjectName("drumTrackLabel_1")
        self.drumTrackLineEdit_1 = QtWidgets.QLineEdit(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLineEdit_1.sizePolicy().hasHeightForWidth())
        self.drumTrackLineEdit_1.setSizePolicy(sizePolicy)
        self.drumTrackLineEdit_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.drumTrackLineEdit_1.setBaseSize(QtCore.QSize(0, 0))
        self.drumTrackLineEdit_1.setReadOnly(True)
        self.drumTrackLineEdit_1.setObjectName("drumTrackLineEdit_1")
        self.selectDrumTrackButton_1 = QtWidgets.QPushButton(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDrumTrackButton_1.sizePolicy().hasHeightForWidth())
        self.selectDrumTrackButton_1.setSizePolicy(sizePolicy)
        self.selectDrumTrackButton_1.setMinimumSize(QtCore.QSize(0, 0))
        self.selectDrumTrackButton_1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectDrumTrackButton_1.setObjectName("selectDrumTrackButton_1")
        self.verticalLayout_2.addWidget(self.splitter_7)
        self.splitter_8 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_8.sizePolicy().hasHeightForWidth())
        self.splitter_8.setSizePolicy(sizePolicy)
        self.splitter_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.drumTrackLabel_2 = QtWidgets.QLabel(self.splitter_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLabel_2.sizePolicy().hasHeightForWidth())
        self.drumTrackLabel_2.setSizePolicy(sizePolicy)
        self.drumTrackLabel_2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.drumTrackLabel_2.setFont(font)
        self.drumTrackLabel_2.setObjectName("drumTrackLabel_2")
        self.drumTrackLineEdit_2 = QtWidgets.QLineEdit(self.splitter_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLineEdit_2.sizePolicy().hasHeightForWidth())
        self.drumTrackLineEdit_2.setSizePolicy(sizePolicy)
        self.drumTrackLineEdit_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.drumTrackLineEdit_2.setBaseSize(QtCore.QSize(0, 0))
        self.drumTrackLineEdit_2.setReadOnly(True)
        self.drumTrackLineEdit_2.setObjectName("drumTrackLineEdit_2")
        self.selectDrumTrackButton_2 = QtWidgets.QPushButton(self.splitter_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDrumTrackButton_2.sizePolicy().hasHeightForWidth())
        self.selectDrumTrackButton_2.setSizePolicy(sizePolicy)
        self.selectDrumTrackButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.selectDrumTrackButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectDrumTrackButton_2.setObjectName("selectDrumTrackButton_2")
        self.verticalLayout_2.addWidget(self.splitter_8)
        self.splitter_10 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_10.sizePolicy().hasHeightForWidth())
        self.splitter_10.setSizePolicy(sizePolicy)
        self.splitter_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.drumTrackLabel_3 = QtWidgets.QLabel(self.splitter_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLabel_3.sizePolicy().hasHeightForWidth())
        self.drumTrackLabel_3.setSizePolicy(sizePolicy)
        self.drumTrackLabel_3.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.drumTrackLabel_3.setFont(font)
        self.drumTrackLabel_3.setObjectName("drumTrackLabel_3")
        self.drumTrackLineEdit_3 = QtWidgets.QLineEdit(self.splitter_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLineEdit_3.sizePolicy().hasHeightForWidth())
        self.drumTrackLineEdit_3.setSizePolicy(sizePolicy)
        self.drumTrackLineEdit_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.drumTrackLineEdit_3.setBaseSize(QtCore.QSize(0, 0))
        self.drumTrackLineEdit_3.setReadOnly(True)
        self.drumTrackLineEdit_3.setObjectName("drumTrackLineEdit_3")
        self.selectDrumTrackButton_3 = QtWidgets.QPushButton(self.splitter_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDrumTrackButton_3.sizePolicy().hasHeightForWidth())
        self.selectDrumTrackButton_3.setSizePolicy(sizePolicy)
        self.selectDrumTrackButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.selectDrumTrackButton_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectDrumTrackButton_3.setObjectName("selectDrumTrackButton_3")
        self.verticalLayout_2.addWidget(self.splitter_10)
        self.splitter_11 = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_11.sizePolicy().hasHeightForWidth())
        self.splitter_11.setSizePolicy(sizePolicy)
        self.splitter_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.drumTrackLabel_4 = QtWidgets.QLabel(self.splitter_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLabel_4.sizePolicy().hasHeightForWidth())
        self.drumTrackLabel_4.setSizePolicy(sizePolicy)
        self.drumTrackLabel_4.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.drumTrackLabel_4.setFont(font)
        self.drumTrackLabel_4.setObjectName("drumTrackLabel_4")
        self.drumTrackLineEdit_4 = QtWidgets.QLineEdit(self.splitter_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumTrackLineEdit_4.sizePolicy().hasHeightForWidth())
        self.drumTrackLineEdit_4.setSizePolicy(sizePolicy)
        self.drumTrackLineEdit_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.drumTrackLineEdit_4.setBaseSize(QtCore.QSize(0, 0))
        self.drumTrackLineEdit_4.setReadOnly(True)
        self.drumTrackLineEdit_4.setObjectName("drumTrackLineEdit_4")
        self.selectDrumTrackButton_4 = QtWidgets.QPushButton(self.splitter_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDrumTrackButton_4.sizePolicy().hasHeightForWidth())
        self.selectDrumTrackButton_4.setSizePolicy(sizePolicy)
        self.selectDrumTrackButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.selectDrumTrackButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.selectDrumTrackButton_4.setObjectName("selectDrumTrackButton_4")
        self.verticalLayout_2.addWidget(self.splitter_11)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.audioTab)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.audioTab)
        self.label_3.setGeometry(QtCore.QRect(310, 30, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.audioTab, "")
        self.metadataTab = QtWidgets.QWidget()
        self.metadataTab.setObjectName("metadataTab")
        self.selectCoverImageButton = QtWidgets.QPushButton(self.metadataTab)
        self.selectCoverImageButton.setGeometry(QtCore.QRect(530, 50, 31, 23))
        self.selectCoverImageButton.setObjectName("selectCoverImageButton")
        self.artistNameLabel = QtWidgets.QLabel(self.metadataTab)
        self.artistNameLabel.setGeometry(QtCore.QRect(20, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.artistNameLabel.setFont(font)
        self.artistNameLabel.setObjectName("artistNameLabel")
        self.descriptionTextEdit = QtWidgets.QTextEdit(self.metadataTab)
        self.descriptionTextEdit.setGeometry(QtCore.QRect(20, 110, 541, 51))
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.coverImageLineEdit = QtWidgets.QLineEdit(self.metadataTab)
        self.coverImageLineEdit.setGeometry(QtCore.QRect(400, 50, 121, 20))
        self.coverImageLineEdit.setReadOnly(True)
        self.coverImageLineEdit.setObjectName("coverImageLineEdit")
        self.coverImageLabel = QtWidgets.QLabel(self.metadataTab)
        self.coverImageLabel.setGeometry(QtCore.QRect(300, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.coverImageLabel.setFont(font)
        self.coverImageLabel.setObjectName("coverImageLabel")
        self.authorNameLabel = QtWidgets.QLabel(self.metadataTab)
        self.authorNameLabel.setGeometry(QtCore.QRect(300, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.authorNameLabel.setFont(font)
        self.authorNameLabel.setObjectName("authorNameLabel")
        self.description = QtWidgets.QLabel(self.metadataTab)
        self.description.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.description.setFont(font)
        self.description.setObjectName("description")
        self.songName = QtWidgets.QLabel(self.metadataTab)
        self.songName.setGeometry(QtCore.QRect(20, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.songName.setFont(font)
        self.songName.setObjectName("songName")
        self.songNameLineEdit = QtWidgets.QLineEdit(self.metadataTab)
        self.songNameLineEdit.setGeometry(QtCore.QRect(110, 20, 161, 20))
        self.songNameLineEdit.setObjectName("songNameLineEdit")
        self.authorNameLineEdit = QtWidgets.QLineEdit(self.metadataTab)
        self.authorNameLineEdit.setGeometry(QtCore.QRect(400, 20, 161, 20))
        self.authorNameLineEdit.setObjectName("authorNameLineEdit")
        self.artistNameLineEdit = QtWidgets.QLineEdit(self.metadataTab)
        self.artistNameLineEdit.setGeometry(QtCore.QRect(110, 50, 161, 20))
        self.artistNameLineEdit.setObjectName("artistNameLineEdit")
        self.tabWidget.addTab(self.metadataTab, "")
        self.setOutputButton = QtWidgets.QPushButton(self.centralwidget)
        self.setOutputButton.setGeometry(QtCore.QRect(460, 320, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.setOutputButton.setFont(font)
        self.setOutputButton.setObjectName("setOutputButton")
        ParadiddleUtilities.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ParadiddleUtilities)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        ParadiddleUtilities.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ParadiddleUtilities)
        self.statusbar.setObjectName("statusbar")
        ParadiddleUtilities.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(ParadiddleUtilities)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ParadiddleUtilities)
        self.tabWidget.setCurrentIndex(0)
        self.midiTrackComboBox.setCurrentIndex(-1)
        self.difficultyComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ParadiddleUtilities)
        ParadiddleUtilities.setTabOrder(self.drumSetLineEdit, self.selectDrumSetButton)
        ParadiddleUtilities.setTabOrder(self.selectDrumSetButton, self.midiFileLineEdit)
        ParadiddleUtilities.setTabOrder(self.midiFileLineEdit, self.selectMidiButton)
        ParadiddleUtilities.setTabOrder(self.selectMidiButton, self.songTrackLineEdit_1)
        ParadiddleUtilities.setTabOrder(self.songTrackLineEdit_1, self.selectSongTrackButton_1)
        ParadiddleUtilities.setTabOrder(self.selectSongTrackButton_1, self.songNameLineEdit)
        ParadiddleUtilities.setTabOrder(self.songNameLineEdit, self.artistNameLineEdit)
        ParadiddleUtilities.setTabOrder(self.artistNameLineEdit, self.authorNameLineEdit)
        ParadiddleUtilities.setTabOrder(self.authorNameLineEdit, self.coverImageLineEdit)
        ParadiddleUtilities.setTabOrder(self.coverImageLineEdit, self.selectCoverImageButton)
        ParadiddleUtilities.setTabOrder(self.selectCoverImageButton, self.descriptionTextEdit)
        ParadiddleUtilities.setTabOrder(self.descriptionTextEdit, self.convertButton)

    def retranslateUi(self, ParadiddleUtilities):
        _translate = QtCore.QCoreApplication.translate
        ParadiddleUtilities.setWindowTitle(_translate("ParadiddleUtilities", "Paradiddle Song Creator"))
        self.convertButton.setText(_translate("ParadiddleUtilities", "Convert to .rlrr!"))
        self.drumSetLabel.setText(_translate("ParadiddleUtilities", "Drum Set:"))
        self.drumSetLineEdit.setText(_translate("ParadiddleUtilities", "defaultset.rlrr"))
        self.selectDrumSetButton.setText(_translate("ParadiddleUtilities", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.drumSetTab), _translate("ParadiddleUtilities", "Drum Set"))
        self.midiFileLabel.setText(_translate("ParadiddleUtilities", "Midi File:"))
        self.selectMidiButton.setText(_translate("ParadiddleUtilities", "..."))
        self.midiTrackLabel.setText(_translate("ParadiddleUtilities", "Midi Track:"))
        self.difficultyLabel.setText(_translate("ParadiddleUtilities", "Difficulty:"))
        self.difficultyComboBox.setCurrentText(_translate("ParadiddleUtilities", "Easy"))
        self.difficultyComboBox.setItemText(0, _translate("ParadiddleUtilities", "Easy"))
        self.difficultyComboBox.setItemText(1, _translate("ParadiddleUtilities", "Medium"))
        self.difficultyComboBox.setItemText(2, _translate("ParadiddleUtilities", "Hard"))
        self.difficultyComboBox.setItemText(3, _translate("ParadiddleUtilities", "Advanced"))
        self.midiMappingLabel.setText(_translate("ParadiddleUtilities", "Midi - Drum Mapping:"))
        self.selectMidiMappingButton.setText(_translate("ParadiddleUtilities", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.midiTab), _translate("ParadiddleUtilities", "MIDI"))
        self.songTrackLabel_1.setText(_translate("ParadiddleUtilities", "Song Track 1"))
        self.selectSongTrackButton_1.setText(_translate("ParadiddleUtilities", "..."))
        self.audioFileLabel_2.setText(_translate("ParadiddleUtilities", "Song Track 2"))
        self.selectSongTrackButton_2.setText(_translate("ParadiddleUtilities", "..."))
        self.songTrackLabel_3.setText(_translate("ParadiddleUtilities", "Song Track 3"))
        self.selectSongTrackButton_3.setText(_translate("ParadiddleUtilities", "..."))
        self.songTrackLabel_4.setText(_translate("ParadiddleUtilities", "Song Track 4"))
        self.selectSongTrackButton_4.setText(_translate("ParadiddleUtilities", "..."))
        self.songTrackLabel_5.setText(_translate("ParadiddleUtilities", "Song Track 5"))
        self.selectSongTrackButton_5.setText(_translate("ParadiddleUtilities", "..."))
        self.drumTrackLabel_1.setText(_translate("ParadiddleUtilities", "Drum Track 1"))
        self.selectDrumTrackButton_1.setText(_translate("ParadiddleUtilities", "..."))
        self.drumTrackLabel_2.setText(_translate("ParadiddleUtilities", "Drum Track 2"))
        self.selectDrumTrackButton_2.setText(_translate("ParadiddleUtilities", "..."))
        self.drumTrackLabel_3.setText(_translate("ParadiddleUtilities", "Drum Track 3"))
        self.selectDrumTrackButton_3.setText(_translate("ParadiddleUtilities", "..."))
        self.drumTrackLabel_4.setText(_translate("ParadiddleUtilities", "Drum Track 4"))
        self.selectDrumTrackButton_4.setText(_translate("ParadiddleUtilities", "..."))
        self.label_2.setText(_translate("ParadiddleUtilities", "Song Tracks"))
        self.label_3.setText(_translate("ParadiddleUtilities", "Drum Tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.audioTab), _translate("ParadiddleUtilities", "Audio Tracks"))
        self.selectCoverImageButton.setText(_translate("ParadiddleUtilities", "..."))
        self.artistNameLabel.setText(_translate("ParadiddleUtilities", "Artist Name:"))
        self.coverImageLabel.setText(_translate("ParadiddleUtilities", "Cover Image:"))
        self.authorNameLabel.setText(_translate("ParadiddleUtilities", "Author Name:"))
        self.description.setText(_translate("ParadiddleUtilities", "Description:"))
        self.songName.setText(_translate("ParadiddleUtilities", "Song Name:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.metadataTab), _translate("ParadiddleUtilities", "Metadata"))
        self.setOutputButton.setText(_translate("ParadiddleUtilities", "Set Output Folder"))
        self.menuAbout.setTitle(_translate("ParadiddleUtilities", "Help"))
        self.actionAbout.setText(_translate("ParadiddleUtilities", "About"))

